# Automatically generated by Pynguin.
import queue_pynguin as module_0


def test_case_0():
    queue_0 = module_0.Queue()
    assert queue_0.queue == []
    set_0 = {queue_0, queue_0, queue_0}
    tuple_0 = set_0,
    var_0 = queue_0.enqueue(tuple_0)
    assert len(queue_0.queue) == 1
    var_1 = queue_0.peek()
    assert var_0 is None
    assert len(var_1) == 1


def test_case_1():
    queue_0 = module_0.Queue()
    assert queue_0.queue == []
    var_0 = queue_0.size()
    var_1 = queue_0.size()
